version: "3.3"
services:
  reverseproxy:
    build:
      context: reverseproxy
    ports:
      - 80:80
    depends_on:
      - alpha
      - ratel
      - graphiql
    restart: on-failure

  keys:
    build:
      context: keys

  graphiql:
    image: npalm/graphiql
    ports:
      - 4000:4000
    environment: 
      API_URL: https://gerrit.lamann.eu/alpha/graphql
    depends_on: 
      - alpha

  lambda:
    image: dgraph/dgraph-lambda:latest
    container_name: lambda
    labels:
      cluster: test
    ports:
      - 8686:8686
    environment:
      DGRAPH_URL: http://alpha:8080
    volumes:
      - type: bind
        source: ./lambda/dist/script.js
        target: /app/script/script.js
        read_only: true
    restart: on-failure

  zero:
    image: dgraph/dgraph:latest
    volumes:
      - ./dgraph-vol:/dgraph-data
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    build:
      context: ./dgraph
      dockerfile: Dockerfile
    volumes:
      - ./dgraph-vol:/dgraph-data
    restart: on-failure
    depends_on: 
      - zero
      - lambda
    ports:
      - 7080:7080
      - 8080:8080
      - 9080:9080
  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
    depends_on:
      - zero
      - alpha
