version: "3.3"
services:
  reverseproxy:
    build:
      context: reverseproxy
    ports:
      - 80:80
    depends_on:
      - alpha
      - ratel
      - graphiql
    restart: on-failure

  keys:
    build:
      context: keys

  graphiql:
    image: npalm/graphiql
    ports:
      - 4000:4000
    environment: 
      API_URL: /alpha/graphql
    depends_on: 
      - alpha

  lambda:
    image: dgraph/dgraph-lambda:latest
    labels:
      cluster: test
      service: lambda
    ports:
      - 8686:8686
    environment:
      DGRAPH_URL: http://alpha:7080
    depends_on:
      - alpha
    volumes:
      - type: bind
        source: ./lambda/dist/script.js
        target: /app/script/script.js
        read_only: true
    restart: on-failure

  zero:
    image: dgraph/dgraph:master
    labels:
      cluster: test
      service: zero
    volumes:
      - ./dgraph-vol:/dgraph-data
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --logtostderr --bindall --expose_trace --profile_mode block --block_rate 10 --my=zero:5080
  
  alpha:
    labels:
      cluster: test
      service: alpha
    build:
      context: ./dgraph
      dockerfile: Dockerfile
    volumes:
      - ./dgraph-vol:/dgraph-data
    restart: on-failure
    depends_on: 
      - zero
    ports:
      - 7080:7080
      - 8080:8080
      - 9080:9080
  
  ratel:
    image: dgraph/dgraph:master
    labels:
      cluster: test
      service: ratel
    ports:
      - 8000:8000
    command: dgraph-ratel
    depends_on:
      - zero
      - alpha
