version: "3.3"
services:
  reverseproxy:
    build:
      context: reverseproxy
    ports:
      - 80:80
    depends_on:
      - alpha
      - ratel
    restart: on-failure

  authorization:
    build:
      context: authorization
    ports:
      - 3000:3000
    depends_on: 
      - alpha
    restart: on-failure

  zero:
    image: dgraph/dgraph:latest
    volumes:
      - ./dgraph-vol:/dgraph-data
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    build:
      context: ./dgraph
      dockerfile: Dockerfile
    volumes:
      - ./dgraph-vol:/dgraph-data
    restart: on-failure
    depends_on: 
      - zero
    ports:
      - 7080:7080
      - 8080:8080
      - 9080:9080
  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
    depends_on:
      - zero
      - alpha